linker: Fix derp from commit ece64014d
error: bionic/linker/Android.bp:169:16: unrecognized property "product_variables.xenonhd"

Change-Id: I1a27f9a0b2db668e339cec1b34e710a5c7f84e58
Signed-off-by: Albert I <krascgq@outlook.co.id>